name: moi_geomaticien
description: Le compagnon méthodologique du géomaticien, par Novateur221.
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/novateur221.png
    - assets/images/moi_geomaticien_logo.png
    - assets/images/app_icon.png
    - assets/images/app_icon_foreground.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FAF7F4"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
